### ISSUE TITLE
SwiftLog Backend

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#1] opened 2020-05-25 09:00 UTC
Evaluate whether it makes sense to build a [Logging](https://github.com/apple/swift-log) `LogHandler` that uses the `Context` as metadata storage.

**Comment by ktoso** [comment] 2020-05-25 09:05
Yup, open question; It would allow us to "pass through" set/get the context metadata if it is being set on a logger, since:

https://github.com/apple/swift-log/blob/master/Sources/Logging/Logging.swift#L76-L84

Though I guess we'd still need to "set" things on the logger metadata if we want any backend to print it...

Good topic to keep in mind 👍

**Comment by ktoso** [comment] 2020-06-25 08:47
This is now Logging performance considerations #38

**Comment by ktoso** [comment] 2020-06-25 08:47
Duplicate of #38

**Closed as completed by ktoso** 2020-06-25 08:47 UTC
Labels: question
